### ISSUE TITLE
comment about wifi setup

### ISSUE THREAD

**Issue by lono** [meinside/rpi-configs#1]
Based on the article http://www.linux-magazine.com/Online/Blogs/Productivity-Sauce/How-to-Quickly-Configure-Wireless-WPA-Connection-on-Raspberry-Pi, I would recommend you to wipe out a "allow-hotplug wlan0" command. For me, the allow-hotplug phrase caused some recognition errors with AWLL5088. How about your usb wifi adapter?

**Comment by meinside** [comment]
Thanks for your recommendation. I thought that line was necessary for plugging it in and out freely while using the box, that was the only reason. Anyway, I don't know if that matters with mine. Will check it out in a while.
