### ISSUE TITLE
error when running prep_go.sh

### ISSUE THREAD

**Issue by SpikeShape** [meinside/rpi-configs#2]
I just executed prep_go.sh on a freshly instaled Raspbian and got the following error:

```
prep_go.sh: 30: prep_go.sh: Syntax error: "}" unexpected
```

**Comment by gregoriomelo** [comment]
I just had the same issue. It happens that I was running `sh prep_go.sh`, which was failing. I got it to work with:

```
chmod +x prep_go.sh
./prep_go.sh
```

Hope it helps

**Comment by meinside** [comment]
As the shebang line says, it is supposed to be run with **bash**.

It won't make any difference on machines which symlink **sh** to bash,
but on my Raspbian(Jessie) sh is linked to **dash**, so it maybe the source of all the problems.

Thanks for pointing it out, @gregoriomelo.

**Comment by SpikeShape** [comment]
Thanks for the input! Worked like a charm.
